export const urls = {
  services: '/service',
  colors: '/color',
  login: '/login',
  check: '/check',
  posts: '/home/posts',
  getUser: '/user',
  updateSimpleUser: '/user',
  adminService: '/admin/service/',
  adminUser: '/admin/user',
  address: '/address/',
  order: '/order',
  orderSingle: '/order/single',
  feedbackFactors: '/feedback/factors',
  cart: '/order/cart',
  pay: '/order/pay',
  paymentVerify: '/order/pay/verify/',
  adminOrder: '/admin/order',
  adminFeedback: '/admin/feedback/',
  adminOrderUpdate: '/admin/order/update',
  ariaWorker: '/order/workers',
  workersOffs: '/user/workerOffs',
  adminLogin: '/admin/login',
  adminDashboard: '/admin/login',
  feedback: '/feedback',
  workerDashboard: '/worker/salary',
  sales: '/admin/dashboard/sales'
};
