export const urls = {
  services: '/service',
  login: '/login',
  check: '/check',
  getUser: '/user',
  updateSimpleUser: '/user',
  adminService: '/admin/service',
  adminUser: '/admin/user',
  address: '/address',
  order: '/order',
  cart: '/order/cart',
  pay: '/order/pay',
  adminOrder: '/admin/order',
  adminOrderUpdate: '/admin/order/update',
  ariaWorker: '/order/workers',
  workersOffs: '/user/workerOffs',
};
